#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Writing',  url: 'writing'}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}
- {name: 'Project Four',  url: 'proj-4'}
- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/thicknavyrain'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'github',    link: 'https://github.com/thicknavyrain'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/ricky-nathvani/'}
# - {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal website for Ricky Nathvanni (Scientist and Writer)'
  # rel-author: 'https://plus.google.com/u/0/#'
  # rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
